export const mockSiteInfo = {
  name: '我的站点',
  description: '在这里发布文章、页面与说说内容。',
  url: 'http://localhost/',
  introTitle: '欢迎来到我的站点',
  introSubtitle: '在这里发布文章、页面与说说内容。',
  hero: {
    enabled: true,
    displayMode: 'inset' as const,
    useImage: false,
    image: '',
    showAvatar: false,
    avatar: '',
    title: '开发者/>, 设计师,\n✦ 细节控, 🎨 创始人',
    subtitle:
      '我是 Cali，👋 在玩 🎮 创始人。目前带领着在玩致力于创造一个充满创造力的工作环境，同时鼓励团队创造影响世界的产品。我热爱开发、设计、创新、享受生活，以及在未知领域中探索。',
    typewriterEnabled: false,
    typewriterInterval: 110,
    typewriterTexts: '',
  },
  theme: {
    primaryColor: '#333333',
    bodyFont: '"MiSans VF", "OPPO Sans", "SF Pro SC", HarmonyOS_Regular, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "PingFang SC", "Segoe UI", "Noto Sans", "Microsoft Yahei", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji"',
    codeFont: '"Fira Code", "Cascadia Code", "JetBrains Mono", "SF Mono", ui-monospace, "Menlo", "Monaco", "Consolas", "Liberation Mono", "Courier New", monospace',
    radius: 'medium' as const,
    shadow: 'small' as const,
    backgroundLight: '#f5f6f7',
    backgroundDark: '#1a1a1a',
    cardLight: '#ffffff',
    cardDark: '#222222',
    foregroundLight: '#333333',
    foregroundDark: '#e0e0e0',
    accentLight: '#f5f5f5',
    accentDark: '#2a2a2a',
    borderLight: '#e2e2e2',
    borderDark: '#333333',
    containerMaxWidth: 1400,
    articleMaxWidth: 900,
    cardMeta: {
      showCategory: true,
      showPublishDate: true,
      showModifiedDate: false,
      showCommentCount: true,
      showViewCount: true,
      showReadingTime: true,
      showWordCount: false,
      showAuthor: true,
    },
  },
  stats: {
    postCount: 25,
    categoryCount: 4,
    tagCount: 4,
    shuoshuoCount: 2,
    totalWordCount: 27746,
    commentCount: 17,
    registeredDate: '2024-01-13T09:00:00',
    lastActivityDate: '2026-04-15T10:00:00',
  },
  socialLinks: [
    { label: '哔哩哔哩', url: 'https://space.bilibili.com/', icon: 'bx bxl-bilibili' },
    { label: 'GitHub', url: 'https://github.com/', icon: 'bx bxl-github' },
    { label: 'Telegram', url: 'https://t.me/', icon: 'bx bxl-telegram' },
  ],
  comments: {
    requireNameEmail: true,
    registrationOnly: false,
    showEmailField: true,
    showUrlField: true,
    showCookiesOptIn: true,
    showImageUpload: true,
  },
  collections: {
    homePostCount: 6,
    homeShuoshuoCount: 3,
    shuoshuoPageSize: 12,
  },
  icp: '沪ICP备2024XXXXXX号',
  icpGov: '沪公网安备 310XXXXXXXXXX号',
}

export const mockMenuItems = [
  {
    id: 1,
    title: '首页',
    url: '/',
    path: '/',
    target: '',
    description: '',
    current: true,
    icon: 'home',
    children: [],
  },
  {
    id: 2,
    title: '说说',
    url: '/shuoshuo',
    path: '/shuoshuo',
    target: '',
    description: '',
    current: false,
    icon: 'chat',
    children: [],
  },
  {
    id: 3,
    title: '关于',
    url: '/about',
    path: '/about',
    target: '',
    description: '',
    current: false,
    icon: 'about',
    children: [],
  },
  {
    id: 4,
    title: '友情链接',
    url: '/links',
    path: '/links',
    target: '',
    description: '',
    current: false,
    icon: 'link',
    children: [],
  },
]

export const mockPosts = [
  {
    id: 1,
    date: '2025-01-15T10:00:00',
    modified: '2025-01-15T10:00:00',
    link: '/hello-world/',
    type: 'post',
    comment_status: 'open' as const,
    title: { rendered: '你好，世界' },
    excerpt: { rendered: '<p>这是我的第一篇文章，欢迎来到我的站点。</p>' },
    categories: ['未分类'],
    tags: [],
    featuredImage: '',
    commentCount: 3,
    viewCount: 128,
    wordCount: 350,
    readingTime: 2,
  },
  {
    id: 2,
    date: '2025-01-14T15:30:00',
    modified: '2025-01-14T16:00:00',
    link: '/wordpress-theme-development/',
    type: 'post',
    comment_status: 'open' as const,
    title: { rendered: 'WordPress 主题开发指南' },
    excerpt: { rendered: '<p>本文介绍如何从零开始开发一个 WordPress 主题。</p>' },
    categories: ['教程'],
    tags: ['WordPress', '主题开发'],
    featuredImage: '',
    commentCount: 5,
    viewCount: 256,
    wordCount: 1200,
    readingTime: 5,
  },
  {
    id: 3,
    date: '2025-01-13T09:00:00',
    modified: '2025-01-13T09:00:00',
    link: '/vue3-composition-api/',
    type: 'post',
    comment_status: 'open' as const,
    title: { rendered: 'Vue 3 组合式 API 入门' },
    excerpt: { rendered: '<p>学习 Vue 3 的组合式 API，提升开发效率。</p>' },
    categories: ['前端'],
    tags: ['Vue', 'JavaScript'],
    featuredImage: '',
    commentCount: 8,
    viewCount: 512,
    wordCount: 2000,
    readingTime: 8,
  },
]

export const mockShuoshuo = [
  {
    id: 101,
    date: '2025-01-15T12:00:00',
    modified: '2025-01-15T12:00:00',
    link: '/shuoshuo/hello/',
    type: 'shuoshuo',
    comment_status: 'open' as const,
    title: { rendered: '第一条说说' },
    excerpt: { rendered: '<p>这是我的第一条说说，记录一下此刻的想法。</p>' },
    categories: [],
    tags: [],
    featuredImage: '',
    commentCount: 1,
    viewCount: 45,
    wordCount: 50,
    readingTime: 1,
  },
  {
    id: 102,
    date: '2025-01-14T18:00:00',
    modified: '2025-01-14T18:00:00',
    link: '/shuoshuo/weekend/',
    type: 'shuoshuo',
    comment_status: 'open' as const,
    title: { rendered: '周末愉快' },
    excerpt: { rendered: '<p>周末到了，好好休息一下吧。</p>' },
    categories: [],
    tags: ['日常'],
    featuredImage: '',
    commentCount: 0,
    viewCount: 32,
    wordCount: 30,
    readingTime: 1,
  },
]

import type { AboutInfo } from '@/types/wordpress'

export const mockAboutInfo: AboutInfo = {
  avatar: 'https://i.pravatar.cc/200',
  subtitleLines: [
    '永恒理想的筑梦师',
    '内心世界的漫游者',
    '情感光谱的翻译官',
    '静谧深海的探险家',
    '精神家园的守护者',
    '理想现实的摆渡人',
  ],
  identityTags: ['计算机爱好者', '博主', '全栈开发者'],
  greeting: '你好，很高兴认识你👋',
  sloganBlock: '在\n不断探索中\n学习·生活·创作',
  skills: ['Java', 'Docker', 'Node.js', 'Vue', 'TypeScript', 'Python', 'Git', 'Linux'],
  timeline: [
    { period: '2020 — 2024', title: '河北农业大学', subtitle: '酿酒工程', image: '' },
    { period: '2024', title: '备考中', subtitle: '待定', image: '' },
    { period: '2025 — 至今', title: '中国铁路北京局集团有限公司', subtitle: '京铁始发站', image: '' },
  ],
  mbtiType: 'INFP-T',
  mbtiLabel: '调停者',
  mbtiImage: '',
  mbtiUrl: 'https://www.16personalities.com/ch/infp-人格',
  games: [
    { name: '原神', icon: '', uid: 'UID: 173516657' },
    { name: '崩坏：星穹铁道', icon: '', uid: 'UID: 100122444' },
    { name: '第五人格', icon: '', uid: 'ID: 442106279' },
  ],
  animeTitle: '时光代理人',
  animeTagline: '不论过去，不问将来',
  musicArtists: 'JUSF周存、HOYO-MIX',
  musicUrl: 'https://music.example.com',
  location: '中国，北京',
  birthYear: 2003,
  education: '河北农业大学酿酒工程',
  occupation: '文创产品运营',
  sponsorTotal: '¥ 1180.44',
  sponsorList: [
    { name: '玖君', amount: '¥ 20' },
    { name: '红中', amount: '¥ 30' },
    { name: '小萌虎', amount: '¥ 65' },
    { name: '匿名用户', amount: '¥ 50' },
  ],
  sponsorUrl: '/sponsor',
  donationWechatQr: '',
  donationAlipayQr: '',
  donationTotal: '总金额：¥ 1180.44，将用于本人各项目的维护和更新',
}

export const mockCategories: Array<{ id: number; name: string; slug: string }> = [
  { id: 1, name: '未分类', slug: 'uncategorized' },
  { id: 2, name: '教程', slug: 'tutorial' },
  { id: 3, name: '前端', slug: 'frontend' },
]

export const mockLinkCategories = [
  {
    id: 1,
    name: '推荐博客',
    slug: 'recommended',
    description: '优秀个人博客推荐',
    links: [
      { id: 1, name: '示例博客', url: 'https://example.com', description: '一个示例博客', image: '', target: '_blank', rating: 5, notes: '常驻' },
      { id: 2, name: '技术笔记', url: 'https://tech-notes.example.com', description: '记录前端技术学习笔记', image: '', target: '_blank', rating: 4, notes: '常驻' },
    ],
  },
  {
    id: 2,
    name: '友情链接',
    slug: 'friends',
    description: '朋友们的站点',
    links: [
      { id: 3, name: '朋友A', url: 'https://friend-a.example.com', description: '朋友A的个人网站', image: '', target: '_blank', rating: 5, notes: '常驻' },
    ],
  },
]
